branches:
  except:
    - /dependabot/ # prevent conflicting builds
os: linux
dist: bionic # based on debian buster
language: python
python:
  - "3.7.3" # latest version on Toolforge Kubernetes
before_install:
  - echo -e "[api]\nemail=good-test-bot@zulipchat.com\nkey=$API_KEY\nsite=https://wikimedia.zulipchat.com" >> ~/zuliprc
  - echo -e "[api]\nemail=irc-test-bot@zulipchat.com\nkey=$API_KEY2\nsite=https://wikimedia.zulipchat.com\n" >> ~/ircbot
  - echo -e "[irc]\nserver=irc.freenode.net\nnickname=zuliptestbot\nchannel=#wikimedia-bots-testing\nnickserv_password=$IRC_PASSWORD\nstream=technical-support\ntopic=General" >> ~/ircbot
install:
  - pip3 install flake8
  - pip3 install -r requirements.txt
  - pip3 install -r requirements-web.txt
script:
  - flake8 --ignore=W191,E117,E501 bots
  - flake8 --ignore=W191,E117,E501 app.py
  - nosetests
notifications:
  webhooks:
    if: branch = master
    urls:
      - http://goodbot.toolforge.org/deploy
    on_success: always
    on_cancel:  never
    on_error:   never