os: linux
dist: bionic # based on debian buster
language: python
python:
  - "3.7.3" # latest version on Toolforge Kubernetes
before_install:
  - echo -e "[api]\nemail=good-test-bot@zulipchat.com\nkey=$API_KEY\nsite=https://wikimedia.zulipchat.com" >> ~/goodbot
  - echo -e "[api]\nemail=irc-bot@zulipchat.com\nkey=$API_KEY2\nsite=https://wikimedia.zulipchat.com" >> ~/ircbot
install:
  - pip3 install flake8
  - pip3 install nose
  - pip3 install -r requirements.txt
script:
  - flake8 --ignore=W191,E117,E501 --show-source bots
  - nosetests